.TH "cache" 3 "Sat Jan 5 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdirecoes\fP"
.br
.ti -1c
.RI "char * \fBpalavra\fP"
.br
.ti -1c
.RI "struct \fBcache\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
