.TH "celula" 3 "Sat Jan 5 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
celula
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "int \fBplinha\fP"
.br
.ti -1c
.RI "int \fBpcoluna\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBnorte\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBsul\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBeste\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBoeste\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBnordeste\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBnoroeste\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBsudeste\fP"
.br
.ti -1c
.RI "struct \fBcelula\fP * \fBsudoeste\fP"
.br
.ti -1c
.RI "int \fBcheck\fP"
.br
.ti -1c
.RI "struct \fBcache\fP * \fBcache1\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
