.TH "palavra" 3 "Sat Jan 5 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
palavra
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "char * \fBppalavra\fP"
.br
.ti -1c
.RI "struct \fBpalavra\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
